# Docker compose for grafana monitoring stack with cadvisor and prometheus
version: "3.7"

services:
  polkadot:
    container_name: polkadot
    image: docker.io/irozuru/polkadot:v1
    restart: always
    ports:
      - 30333:30333/tcp # p2p port
      - 9933:9933/tcp # rpc port
      - 9944:9944/tcp # ws port
    volumes:
      - ./node-data:/node-data
    command: 
      - --rpc-external
      - --ws-external
      - --rpc-cors
      - all
      - --chain=kusama
      - --pruning
      - archive
      - -d
      - /node-data/
    networks:
      - kusama-net
      
  substrate:
    container_name: substrate
    image: parity/substrate-api-sidecar
    restart: always
    environment:
      SAS_SUBSTRATE_WS_URL: ws://polkadot:9944
    links:
      - polkadot:polkadot
    networks:
      - kusama-net
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./node-data:/var/lib/grafana
    networks:
      - kusama-net
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./node-data:/var/lib/prometheus
    networks:
      - kusama-net
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    restart: always
    ports:
      - 8080:8080
    networks:
      - kusama-net
  nodeexporter:
    container_name: nodeexporter
    image: prom/node-exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - kusama-net

    
networks:
  kusama-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.103.0.1/16

