plugin: aws_ec2
aws_access_key:  "${{ AWS_ACCESS_KEY_ID }}"
aws_secret_key: "${{ AWS_SECRET_ACCESS_KEY }}"
regions:
  - us-east-1
  - us-east-2

# Ignores 403 errors rather than failing
strict_permissions: False
keyed_groups:
  - key: tags
    prefix: tag