name: Ansible Actions

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
     
      - name: Install prerequisites
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false" 
        run: |
          # sudo apt-get install python3 -y
          # sudo apt-get install python3-pip -y
          # python -m pip install --upgrade pip
          # pip install awscli 
          # pip install boto
          # pip install boto3
          # pip install bs4
          # ansible-playbook -i inventory/aws_ec2.yml --extra-vars @secrets/secrets.yml  --user ubuntu -vvvv main.yml
          