- name: Create keyrings parity directory (/usr/share/keyrings/)
  file:
    path: "/usr/share/keyrings/"
    state: directory 

- name: Create etcd systemd directory (/etc/systemd/system)
  file:
    path: '/etc/systemd/system'
    state: directory                      

    # DOWNLOAD BINARIES 
- name: Import the security@parity.io GPG key
  vars:
    GPG_KEY: '9D4B2B6EB8F97156D19669A9FF0812D491B96798'
  shell:
        "gpg --recv-keys --keyserver keyserver.ubuntu.com {{GPG_KEY}}"

- name: export the security@parity.io GPG key
  vars:
    GPG_KEY: '9D4B2B6EB8F97156D19669A9FF0812D491B96798' 
  shell: gpg --export {{ GPG_KEY }} > /usr/share/keyrings/parity.gpg

    # # Add the Parity repository and update the package index    
- name: Add the Parity repository and update the package index 
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/parity.gpg] https://releases.parity.io/deb release main
    filename: parity
    state: present

- name: Ansible apt-get to get install polkadot
  apt:
    state: present
    name: 
      - parity-keyring
      - polkadot

    # CONFIGURE POLKADOT SYSTEMD SERVICE
- name: Copy systemd init file
  copy:
    src: ./templates/collatornode.service
    dest: /etc/systemd/system/collatornode.service

- name: Start polkadot collator node service
  systemd:
    name: collatornode.service
    state: started
    enabled: yes