apiVersion: v1
kind: Service
metadata:
  name: polkadot-kusama-svc
  namespace: staging
  labels:
    service: kusama
spec:
  ports:
  - name: 
    port: 9933
    targetPort: 9933
    protocol: TCP

  - name: 
    protocol: TCP
    port: 30333
    targetPort: 30333

  - name: 
    protocol: TCP
    port: 30334
    targetPort: 30334

  selector:
    app: kusama