# - name: Boot node config setup
#   hosts: boot-nodes
#   become: yes
#   become_user: root
#   roles: 
#     - boot-node

- name: Collator node setup
  hosts: collator-nodes
  become: yes
  become_user: root
  roles:
    - collator-node

- name: Rpc node setup
  hosts: rpc-nodes
  become: yes
  become_user: root
  roles:
    - rpc-node
 

