# - name: monitoring
#   become: yes
#   become_user: root
#   hosts: all
#   roles:
#     - prometheus
#     - node-exporter

- name: grafana
  become: yes
  become_user: root
  hosts: 'collator-nodes'
  roles:
    - grafana