name: Ansible Actions

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false" 
        run: |
          ansible-playbook -i config/aws_ec2.yml -e 'ansible_python_interpreter=/usr/bin/python3' -vvvv main.yml
        working-directory: ./IAC/Ansible

       
          